AWSTemplateFormatVersion: 2010-09-09

Description: Plantilla para lanzar una instancia EC2 y habilitar SSH

Parameters: 
  KeyName:
    Description: Nombre del SSH KeyPair
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: Provide the name of an existing SSH key pair

Resources:
  AsesoresTIEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-04b70fa74e45c3917
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: AsesoresTIEC2

    # Se instalan las dependencias necesarias para ejecutar apache
    # y para clonar un repositorio de GitHub
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update -y
          apt-get install -y apache2
          systemctl start apache2
          systemctl enable apache2
          apt-get install -y git
          cd /var/www/html
          git clone https://github.com/josearcos2023/sn_semana08_2.git

  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: DMZSecurityGroup
      GroupDescription: Habilitar acceso SSH  via puerto 22
      SecurityGroupIngress:
        IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0

  VPCLab16:
    Type: 'AWS::EC2::VPC'
    Properties: 
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: MyVPC

  Subnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPCLab16
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: MySubnet

  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: MyInternetGateway

  AttachGateway:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref VPCLab16
      InternetGatewayId: !Ref InternetGateway

  RouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPCLab16
      Tags:
        - Key: Name
          Value: PublicRouteTable

  Route:
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
    DependsOn: AttachGateway

  SubnetRouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref Subnet
      RouteTableId: !Ref RouteTable

  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: bucket-arcos-balboa-lab16
      Tags:
        - Key: Name
          Value: MyS3Bucket
Outputs: 
  InstanceID:
    Description: Instance ID
    Value: !Ref AsesoresTIEC2Instance

  BucketName:
    Description: S3 Bucket Name
    Value: !Ref S3Bucket

  VpcId:
    Description: VPC ID
    Value: !Ref VPCLab16

  SubnetId:
    Description: Subnet ID
    Value: !Ref Subnet

  SecurityGroupId:
    Description: Security Group ID
    Value: !Ref InstanceSecurityGroup